version: "3"
services:
  db:
    image:  postgres
    restart: always 
    ports:
        #  if wanna change port ONLY change first number!!
      - "5433:5432"
    environment:
       POSTGRES_PASSWORD: pass123 